# Generated by Django 2.2.24 on 2022-02-21 00:23

from django.db import migrations

from property.models import Flat


def set_new_building(app, schema_editor):
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building)
    ]
