# Generated by Django 2.2.24 on 2022-02-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
