# Generated by Django 2.2.24 on 2022-02-21 01:51

import phonenumbers
from django.db import migrations
from property.models import Flat


def set_owner_pure_phone(app, schema_editor):
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.format_number(
            phonenumbers.parse(flat.owners_phonenumber, "RU"),
            phonenumbers.PhoneNumberFormat.E164
        )

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone)
    ]
