# Generated by Django 2.2.24 on 2022-02-21 01:51

import phonenumbers
from django.db import migrations
from property.models import Flat


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
    ]
