# Generated by Django 2.2.24 on 2022-02-21 02:06

import phonenumbers
from django.db import migrations
from property.models import Flat


def set_owner_pure_phone(app, schema_editor):
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                phonenumber,
                phonenumbers.PhoneNumberFormat.E164
            )

            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220221_0501'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone)
    ]
