# Generated by Django 2.2.24 on 2022-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='property_apartments',
            field=models.ManyToManyField(related_name='apartments', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
