# Generated by Django 2.2.24 on 2022-02-21 02:43

from django.db import migrations
from property.models import Flat, Owner


def create_data_on_owner(app, schema_editor):
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            defaults={
                'owner': flat.owner,
                'owners_phonenumber': flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220221_0537'),
    ]

    operations = [
        migrations.RunPython(create_data_on_owner)
    ]
