# Generated by Django 2.2.24 on 2022-02-21 02:58

from django.db import migrations
from property.models import Flat, Owner


def create_data_on_owner(app, schema_editor):
    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber
        )
        owner.property_apartments.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220221_0543'),
    ]

    operations = [
        migrations.RunPython(create_data_on_owner)
    ]
