# Generated by Django 2.2.24 on 2022-02-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220221_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='user',
            new_name='client',
        ),
    ]
