# Generated by Django 2.2.24 on 2022-02-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20220221_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_claims', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_claims', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
    ]
