# Generated by Django 2.2.24 on 2022-02-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20220221_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='property_apartments',
            field=models.ManyToManyField(related_name='apartment_owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
